export const DEFAULT_LOW_STOCK_THRESHOLD = 10;
export const DEFAULT_PAGE_SIZE = 20;

// Auth
export const JWT_SECRET = process.env.JWT_SECRET || "inkly-jwt-secret-dev-only";

export enum UserRole {
  CITIZEN = "CITIZEN",
  STAFF = "STAFF",
  ADMIN = "ADMIN",
  BARANGAY_POLICE = "BARANGAY_POLICE",
}

// Applications
export enum ApplicationType {
  BARANGAY_CLEARANCE = "BARANGAY_CLEARANCE",
  CERTIFICATE_OF_RESIDENCY = "CERTIFICATE_OF_RESIDENCY",
  BUSINESS_PERMIT = "BUSINESS_PERMIT",
  INDIGENCY_CERTIFICATE = "INDIGENCY_CERTIFICATE",
  CEDULA = "CEDULA",
}

export enum ApplicationStatus {
  SUBMITTED = "SUBMITTED",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  READY_FOR_PICKUP = "READY_FOR_PICKUP",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
}

// Equipment Reservations
export enum EquipmentType {
  CHAIR = "CHAIR",
  TABLE = "TABLE",
  TENT = "TENT",
  SOUND_SYSTEM = "SOUND_SYSTEM",
  LIGHTS = "LIGHTS",
  STAGE_PANEL = "STAGE_PANEL",
}

export enum EventType {
  BIRTHDAY = "BIRTHDAY",
  WEDDING = "WEDDING",
  BURIAL = "BURIAL",
  COMMUNITY_EVENT = "COMMUNITY_EVENT",
  SPORTS_EVENT = "SPORTS_EVENT",
  MEETING = "MEETING",
  OTHER = "OTHER",
}

export enum EquipmentReservationStatus {
  SUBMITTED = "SUBMITTED",
  FOR_DELIVERY = "FOR_DELIVERY",
  COMPLETED = "COMPLETED",
  REJECTED = "REJECTED",
  CANCELLED = "CANCELLED",
}

// E-Sumbong (Reports)
export enum ReportType {
  CRIME = "CRIME",
  NOISE_COMPLAINT = "NOISE_COMPLAINT",
  PUBLIC_SAFETY = "PUBLIC_SAFETY",
  INFRASTRUCTURE = "INFRASTRUCTURE",
  HEALTH_HAZARD = "HEALTH_HAZARD",
  STRAY_ANIMALS = "STRAY_ANIMALS",
  ILLEGAL_ACTIVITY = "ILLEGAL_ACTIVITY",
  ENVIRONMENTAL = "ENVIRONMENTAL",
  OTHER = "OTHER",
}

export enum ReportStatus {
  SUBMITTED = "SUBMITTED",
  ACKNOWLEDGED = "ACKNOWLEDGED",
  INVESTIGATING = "INVESTIGATING",
  RESOLVED = "RESOLVED",
  CLOSED = "CLOSED",
  DISMISSED = "DISMISSED",
}

export enum ReportSeverity {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  EMERGENCY = "EMERGENCY",
}
